In [179]:
import numpy as np

In [180]:
weather = pd.read_csv("C:/WORKSPACE/db/data-files/weather_data.csv")

In [181]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42016 entries, 0 to 42015
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   지점번호     42016 non-null  int64  
 1   지점명      42016 non-null  object 
 2   일시       42016 non-null  object 
 3   평균기온(℃)  41260 non-null  float64
 4   최고기온(℃)  41257 non-null  float64
 5   최고기온시각   29182 non-null  object 
 6   최저기온(℃)  41257 non-null  float64
 7   최저기온시각   29172 non-null  object 
 8   일교차      41256 non-null  float64
dtypes: float64(4), int64(1), object(4)
memory usage: 2.9+ MB


In [182]:
weather['일시'] = pd.to_datetime(weather['일시'])

In [183]:
weather.isnull().sum()

지점번호           0
지점명            0
일시             0
평균기온(℃)      756
최고기온(℃)      759
최고기온시각     12834
최저기온(℃)      759
최저기온시각     12844
일교차          760
dtype: int64

In [184]:
print(weather)

       지점번호 지점명         일시  평균기온(℃)  최고기온(℃) 최고기온시각  최저기온(℃) 최저기온시각   일교차
0       108  서울 1907-10-01     13.5     20.7    NaN      7.9    NaN  12.8
1       108  서울 1907-10-02     16.2     22.0    NaN      7.9    NaN  14.1
2       108  서울 1907-10-03     16.2     21.3    NaN     13.1    NaN   8.2
3       108  서울 1907-10-04     16.5     22.0    NaN     11.2    NaN  10.8
4       108  서울 1907-10-05     17.6     25.4    NaN     10.9    NaN  14.5
...     ...  ..        ...      ...      ...    ...      ...    ...   ...
42011   108  서울 2023-12-13      6.8     10.3  14:59      2.6  04:19   7.7
42012   108  서울 2023-12-14      7.6      9.1  01:27      6.2  23:15   2.9
42013   108  서울 2023-12-15      4.9      6.2  00:01      3.7  23:59   2.5
42014   108  서울 2023-12-16     -4.1      3.8  00:01     -9.9  24:00  13.7
42015   108  서울 2023-12-17     -9.8     -6.4  14:52    -12.4  07:58   6.0

[42016 rows x 9 columns]


In [185]:
weather_day = weather[['일시']].to_numpy()
weather_temp = weather[['평균기온(℃)', '최고기온(℃)', '최저기온(℃)']].to_numpy()

In [186]:
a = np.nanargmax(weather_temp[:, 1])
b = np.nanargmin(weather_temp[:, 2])

In [187]:
print(weather_temp[a])
print(weather_temp[b])

[33.6 39.6 27.8]
[-15.3  -6.4 -23.1]


In [188]:
sub = np.subtract(weather_temp[:,1], weather_temp[:,2])

In [189]:
c = np.nanargmax(sub)

In [190]:
print(weather_temp[c])

[12.7 24.3  2.5]


In [191]:
weather_mean = np.nanmean(weather_temp, axis = 0)

In [192]:
print(weather_mean)

[11.79874455 16.80011634  7.51011465]
