In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

In [ ]:
N = 10
K = 4
mu_0 = np.ones(K) / K
print(mu_0)

np.random.seed(42)
x = np.random.choice(K, N, p=mu_0) 
print(x)

c = np.bincount(x)
print(c)

stats.chisquare(x)


[0.25 0.25 0.25 0.25]
[1 3 2 2 0 0 0 3 2 2]
[3 1 4 2]


Power_divergenceResult(statistic=np.float64(8.333333333333332), pvalue=np.float64(0.5009344477491052))