In [19]:
import numpy as np
import pandas as pd

In [20]:
df2 = pd.DataFrame([
    ['green', 'M', 10.1, 'class1'],
    ['red', 'L', 13.5, 'class2'],
    ['blue', 'XL', 15.3, 'class1'],
])
df2.columns = ['color', 'size', 'price', 'classlabel']
df2

color size  price classlabel
0  green    M   10.1     class1
1    red    L   13.5     class2
2   blue   XL   15.3     class1

In [21]:
# np.unique(df2['classlabel'], return_counts=True)
# df2['classlabel'].unique()

# class_mapping = { 'class1' : 0, 'class2' : 1, 'class3' : 2} # 순위형 범주 데이터
class_mapping = {
    label : idx for idx, label in enumerate(np.unique(df2['classlabel']))
}
class_mapping
df2['classlabel2'] = df2['classlabel'].map(class_mapping)
df2

color size  price classlabel  classlabel2
0  green    M   10.1     class1            0
1    red    L   13.5     class2            1
2   blue   XL   15.3     class1            0

In [22]:
inv_class_mapping = { v : k for k, v in class_mapping.items() }
print(inv_class_mapping)
df2['classlabel2'] = df2['classlabel2'].map(inv_class_mapping)
df2

{0: 'class1', 1: 'class2'}


color size  price classlabel classlabel2
0  green    M   10.1     class1      class1
1    red    L   13.5     class2      class2
2   blue   XL   15.3     class1      class1

In [23]:
from sklearn.preprocessing import LabelEncoder
class_le = LabelEncoder()
y = class_le.fit_transform(df2['classlabel'].values)
y
df2['classlabel'] = class_le.fit_transform(df2['classlabel'].values)
df2


color size  price  classlabel classlabel2
0  green    M   10.1           0      class1
1    red    L   13.5           1      class2
2   blue   XL   15.3           0      class1

In [27]:
color_le = LabelEncoder()
X[:, 0] = color_le.fit_transform(X[:, 0])
X


array([[1, 10.1],
       [2, 13.5],
       [0, 15.3]], dtype=object)

In [26]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder() # 0번째 컬럼 Encoding
encoded = ohe.fit_transform(X[:, [0]]).toarray()
encoded

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [29]:
pd.get_dummies(df2[['price', 'color']])

price  color_blue  color_green  color_red
0   10.1       False         True      False
1   13.5       False        False       True
2   15.3        True        False      False

In [32]:
df_wine = pd.read_csv('D:/humanda/WORKSPACE/da-basic/data-files/winequality-white.csv', sep=";")

In [33]:
df_wine.head(10)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   
5            8.1              0.28         0.40             6.9      0.050   
6            6.2              0.32         0.16             7.0      0.045   
7            7.0              0.27         0.36            20.7      0.045   
8            6.3              0.30         0.34             1.6      0.049   
9            8.1              0.22         0.43             1.5      0.044   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   
5                 30.0                  97.0   0.9951  3.26       0.44   
6                 30.0                 136.0   0.9949  3.18       0.47   
7                 45.0                 170.0   1.0010  3.00       0.45   
8                 14.0                 132.0   0.9940  3.30       0.49   
9                 28.0                 129.0   0.9938  3.22       0.45   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6  
5     10.1        6  
6      9.6        6  
7      8.8        6  
8      9.5        6  
9     11.0        6

In [36]:
from sklearn.model_selection import train_test_split

X, y = df_wine.iloc[:, :-1].values, df_wine.iloc[:, -1].values
X_train, X_test, y_train, y_test = \
    train_test_split(X, y, test_size=0.3, random_state=42, stratify= y)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((3428, 11), (1470, 11), (3428,), (1470,))

In [37]:
np.unique(y_test, return_counts = True)

(array([3, 4, 5, 6, 7, 8, 9]), array([  6,  49, 437, 660, 264,  53,   1]))